theme: minima
title: Elkana Langat's personal blog
description: >-
  Welcome to my tech blog and portfolio. I'm Elkana Lang'at, a cloud security enthusiast 
  certified in AWS and Microsoft fundamentals, currently diving deeper into identity, threat 
  protection, and security engineering in the cloud. Here, I share my learning journey, projects, 
  certifications, and experiences in cybersecurity and cloud computing.
author: elkana-langat
